# Generated by Django 5.2.15 on 2026-06-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        max_length=20,
                    ),
                ),
                ("external_lesson_id", models.CharField(blank=True, max_length=255)),
                ("cards_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("card_kind", models.CharField(blank=True, max_length=20)),
                ("source_language", models.CharField(blank=True, max_length=100)),
                ("target_language", models.CharField(blank=True, max_length=100)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "external_id"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_card_id", models.CharField(max_length=255)),
                ("native_value", models.TextField(blank=True)),
                ("correct_value", models.TextField(blank=True)),
                ("hint", models.TextField(blank=True)),
                ("mistake", models.TextField(blank=True)),
                ("card_kind", models.CharField(blank=True, max_length=20)),
                ("source_language", models.CharField(blank=True, max_length=100)),
                ("target_language", models.CharField(blank=True, max_length=100)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("stars", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "external_card_id", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson", "external_card_id"),
                        name="unique_card_external_id_per_lesson",
                    )
                ],
            },
        ),
    ]
