# Generated by Django 5.2.16 on 2026-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_owner_alter_lesson_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthAllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('google_sub', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email', 'google_sub', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('google_sub', ''), _negated=True), _connector='OR'), name='google_oauth_allowlist_has_identity')],
            },
        ),
    ]
