# Generated by Django 5.2.16 on 2026-07-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_googleoauthalloweduser'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='googleoauthalloweduser',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='google_oauth_unique_allowed_email'),
        ),
        migrations.AddConstraint(
            model_name='googleoauthalloweduser',
            constraint=models.UniqueConstraint(condition=models.Q(('google_sub', ''), _negated=True), fields=('google_sub',), name='google_oauth_unique_allowed_sub'),
        ),
    ]
