# Generated by Django 5.2.15 on 2026-07-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_user_policies(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AdminMfaPolicy = apps.get_model("lessons", "AdminMfaPolicy")
    AdminMfaPolicy.objects.bulk_create(
        [AdminMfaPolicy(user_id=user_id) for user_id in User.objects.values_list("id", flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_googleoauthalloweduser_google_oauth_unique_allowed_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMfaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_required', models.BooleanField(default=False, help_text='When enabled, this staff user must enroll and use TOTP to enter Django Admin.', verbose_name='Require admin 2FA')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_mfa_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin 2FA policy',
                'verbose_name_plural': 'admin 2FA policies',
                'ordering': ['user__username'],
                'permissions': [('reset_staff_mfa', 'Can reset staff MFA')],
            },
        ),
        migrations.RunPython(create_existing_user_policies, migrations.RunPython.noop),
    ]
