# Generated by Django 5.2.15 on 2026-07-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_user_records(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserSecurityProfile = apps.get_model("lessons", "UserSecurityProfile")
    Subscription = apps.get_model("lessons", "Subscription")
    user_ids = list(User.objects.values_list("id", flat=True))
    UserSecurityProfile.objects.bulk_create(
        [UserSecurityProfile(user_id=user_id) for user_id in user_ids],
        ignore_conflicts=True,
    )
    Subscription.objects.bulk_create(
        [Subscription(user_id=user_id) for user_id in user_ids],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_adminmfapolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin audit event',
                'verbose_name_plural': 'admin audit log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive values add credits; negative values spend or revoke them.')),
                ('reason', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('support_bonus', 'Support bonus'), ('admin_adjustment', 'Admin adjustment'), ('reversal', 'Reversal')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_credit_entries', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='lessons.creditledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('issue_credit_adjustment', 'Can issue controlled credit adjustments')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(default='free', max_length=64)),
                ('status', models.CharField(choices=[('free', 'Free'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='free', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'permissions': [('manage_subscription_status', 'Can perform subscription status actions')],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_break_glass', models.BooleanField(default=False, help_text='Emergency owner account that must not be used for daily work.')),
                ('internal_note', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('access_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user security profile',
                'verbose_name_plural': 'user security profiles',
                'permissions': [('manage_user_status', 'Can block, unblock, and soft-delete users'), ('adjust_credits', 'Can issue and revoke credit adjustments'), ('manage_subscriptions', 'Can change subscription status')],
            },
        ),
        migrations.RunPython(create_existing_user_records, migrations.RunPython.noop),
    ]
