<?php defined('ABSPATH') || exit; get_header(); ?>
<section class="hero"><div class="hero-copy"><div class="eyebrow">CODZIENNOŚĆ W DOBRYM KOLORZE</div><h1>Szczoteczki<br>od <em>Pani Ewy</em><span>.</span></h1><p>Mały rytuał, wielka przygoda.<br>Wybierz kolorowy początek i dodaj trochę radości do codziennego szczotkowania.</p><div class="hero-actions"><a href="#produkty" class="btn">Zobacz szczoteczki <span aria-hidden="true">↗</span></a><button class="btn secondary" data-video><span aria-hidden="true">▷</span> Poznaj historię</button></div><p class="hero-note"><span>✦ Kolorowe inspiracje</span><span>✦ Wspólny koszyk</span></p></div><div class="hero-art"><div class="hero-photo"><img src="<?php echo esc_url(odp_asset('hero-fixed.png')); ?>" width="941" height="1672" alt="Komiksowa Pani Ewa i rudowłosy chłopiec w kasku" fetchpriority="high"></div><span class="comic-label">Hej, uśmiechnij się!</span><span class="comic-label pink">Mały rytuał. Wielka moc!</span><span class="spark" aria-hidden="true">✦</span><span class="bubble" aria-hidden="true"></span></div></section>
<div class="promise-strip"><span><b>✦</b> Świat Pani Ewy</span><span><b>◇</b> Jeden wspólny koszyk</span><span><b>↗</b> Testuj bez płacenia</span></div>
<?php $featured = function_exists('odp_growth_featured') ? odp_growth_featured() : false; if ($featured): ?>
<section class="section"><div class="section-heading"><div><div class="eyebrow">WYBÓR PANI EWY</div><h2>Mały rytuał, wielki uśmiech.</h2><p>Nasz główny produkt - poznaj go bliżej.</p></div></div>
<div class="featured"><a class="featured-visual" href="<?php echo esc_url($featured->get_permalink()); ?>"><?php echo $featured->get_image(); ?><?php if (!$featured->get_image_id()): ?><span class="art-caption">Ilustracja poglądowa, nie zdjęcie SKU</span><?php endif; ?></a><div class="featured-copy"><span class="tag purple">WYBÓR PANI EWY</span><h3><?php echo esc_html($featured->get_name()); ?></h3><?php echo wp_kses_post(wpautop($featured->get_short_description())); ?><strong class="price"><?php echo wp_kses_post($featured->get_price_html()); ?></strong><p class="tiny">Cena i produkt demonstracyjny.</p><a class="btn purple" href="<?php echo esc_url($featured->get_permalink()); ?>">Zobacz produkt ↗</a></div></div></section>
<?php endif; ?>
<?php $coupon = function_exists('odp_growth_coupon') ? odp_growth_coupon() : false; if ($coupon): ?>
<div class="section"><div class="coupon-strip"><span><strong>Mała niespodzianka na start!</strong><br>Wpisz kod w koszyku. Rabat zależy od produktów i warunków kuponu.</span><span class="coupon-code"><?php echo esc_html($coupon->get_code()); ?></span></div></div>
<?php endif; ?>
<section class="section odp-woo" id="produkty"><div class="section-heading"><div><div class="eyebrow">MAŁY WYBÓR, WIELE KOLORÓW</div><h2>Znajdź swój kolor uśmiechu</h2><p>Produkty demonstracyjne. Bez płatności i wysyłki.</p></div></div>
<?php $choices = function_exists('odp_growth_alternatives') ? odp_growth_alternatives() : []; if ($choices) echo do_shortcode('[products ids="' . implode(',', array_map('absint', $choices)) . '" columns="3" orderby="post__in"]'); ?>
<?php $category_link = function_exists('odp_growth_category') && odp_growth_category() ? get_term_link(odp_growth_category(), 'product_cat') : false; if ($category_link && !is_wp_error($category_link)): ?><p><a class="btn secondary" href="<?php echo esc_url($category_link); ?>">Zobacz wszystkie produkty ↗</a></p><?php endif; ?></section>
<section class="story-section"><div class="story-inner"><button class="story-poster" data-video aria-label="Odtwórz historię Pani Ewy"><img src="<?php echo esc_url(odp_asset('poster.webp')); ?>" alt="Kadr z komiksowej historii Pani Ewy" loading="lazy" width="500" height="889"><span class="play"><span>▷</span></span></button><div class="story-copy"><div class="eyebrow">POZNAJ NASZ ŚWIAT</div><h2>Każdy uśmiech<br>ma swoją historię.</h2><p>Pani Ewa, mały bohater i odrobina komiksowej magii. Zobacz, od czego zaczęła się ta przygoda.</p><button class="btn" data-video>Obejrzyj historię <span aria-hidden="true">▷</span></button><p class="tiny">Film uruchamiasz samodzielnie. Ilustracja, nie prezentacja SKU.</p></div></div></section>
<section class="section faq-wrap"><div class="faq"><h2>Dobrze wiedzieć.</h2><details><summary>Czy mogę już kupić produkt?</summary><p>Jeszcze nie. Możesz złożyć wyłącznie zamówienie testowe. Nie pobieramy opłat i nie wysyłamy produktów.</p></details><details><summary>Jak użyć kodu rabatowego?</summary><p>Wpisz kod w koszyku i zatwierdź. Sklep sprawdzi jego ważność oraz produkty objęte promocją. Wysokość rabatu zobaczysz przed złożeniem zamówienia.</p></details><details><summary>Czy działa już InPost Pay?</summary><p>Nie. Integracja płatności i rzeczywistych przesyłek będzie osobnym etapem.</p></details></div></section>
<?php get_footer(); ?>
