ServerName localhost
ServerTokens Prod
ServerSignature Off
<IfModule mpm_prefork_module>
    StartServers 2
    MinSpareServers 1
    MaxSpareServers 2
    MaxRequestWorkers 4
    MaxConnectionsPerChild 300
</IfModule>
<Directory /var/www/html/wp-content/uploads>
    <FilesMatch "\.(php[0-9]?|phtml|phar)$">
        Require all denied
    </FilesMatch>
</Directory>
<Directory /var/www/html/assets>
    Options -Indexes -ExecCGI
    <FilesMatch "\.(php[0-9]?|phtml|phar)$">
        Require all denied
    </FilesMatch>
</Directory>
