<?php
// Dedicated disposable CI database only. Never run this against the live store.
defined('WP_CLI') && WP_CLI || exit;
if (getenv('ODP_CI') !== '1' || home_url('/') !== 'http://127.0.0.1:8089/') WP_CLI::error('Requires the disposable local CI store.');
require_once ABSPATH . 'wp-admin/includes/template.php';
$check = function ($condition, $message) {
    if (!$condition) WP_CLI::error($message);
    WP_CLI::log('PASS: ' . $message);
};
$id = function ($sku) { return wc_get_product_id_by_sku($sku); };
$main = $id('DEMO-BRUSH-01');
$a = $id('DEMO-BRUSH-02');
$b = $id('DEMO-BRUSH-03');
$c = $id('DEMO-BRUSH-04');
$d = $id('DEMO-BRUSH-05');
$paste = $id('DEMO-PASTE-01');
$category = odp_growth_category();
$check(odp_growth_featured()->get_id() === $main, 'Default hero is preserved');
$check(odp_growth_alternatives() === [$a, $b, $c], 'Default three choices exclude hero');
$check(get_option('woocommerce_feature_order_attribution_enabled') === 'yes', 'Native order attribution enabled');
$privacy = get_page_by_path('prywatnosc');
$check(!str_contains($privacy->post_content, 'Nie używamy analityki'), 'Seed privacy text updated for session attribution');
$input = ['category' => $category, 'featured' => $main, 'alternatives' => [$a, $main, $paste, $b, $b, $c, $d], 'coupon' => 'WIOSNA', 'seo_title' => '<b>Test</b>', 'seo_description' => '<img src=x onerror=alert(1)>Opis'];
$saved = odp_growth_sanitize($input);
$check($saved['alternatives'] === [$a, $b, $c], 'Duplicate, hero and wrong-category products excluded; limit enforced');
$check($saved['seo_title'] === 'Test' && !str_contains($saved['seo_description'], '<'), 'SEO text removes HTML');
update_option('odp_growth', $saved);
$check(odp_growth_alternatives() === [$a, $b, $c], 'Selection survives persistence');
$hidden = wc_get_product($a);
$hidden->set_status('draft');
$hidden->save();
$check(odp_growth_alternatives() === [$b, $c], 'Draft products never leak through a saved selection');
$hidden->set_status('publish');
$hidden->save();
$saved['featured'] = $b;
$saved['alternatives'] = [$d, $a];
update_option('odp_growth', $saved);
$check(odp_growth_featured()->get_id() === $b && odp_growth_alternatives() === [$d, $a], 'Changing the hit and ordering alternatives works');
$saved['featured'] = 0;
$saved['alternatives'] = [];
update_option('odp_growth', $saved);
$check(!odp_growth_featured() && odp_growth_alternatives() === [], 'Cleared selections do not silently reappear');
$check(odp_growth_coupon()->get_id() > 0, 'Existing coupon visible');
$coupon = new WC_Coupon('WIOSNA');
$coupon->set_date_expires(time() - 3600);
$coupon->save();
$check(!odp_growth_coupon(), 'Expired coupon banner hidden');
$coupon->set_date_expires(null);
$coupon->set_usage_limit(1);
$coupon->set_usage_count(1);
$coupon->save();
$check(!odp_growth_coupon(), 'Exhausted coupon banner hidden');
$coupon->set_usage_limit(0);
$coupon->set_usage_count(0);
$coupon->save();
$saved['coupon'] = '';
update_option('odp_growth', $saved);
$check(!odp_growth_coupon(), 'Coupon banner can be disabled');
$user = wp_insert_user(['user_login' => 'ci-customer', 'user_pass' => wp_generate_password(), 'role' => 'customer']);
wp_set_current_user($user);
ob_start(); odp_growth_admin(); $html = ob_get_clean();
$check($html === '', 'Customer cannot render management controls');
$manager = wp_insert_user(['user_login' => 'ci-manager', 'user_pass' => wp_generate_password(), 'role' => 'shop_manager']);
wp_set_current_user($manager);
$check(current_user_can(apply_filters('option_page_capability_odp_growth_group', 'manage_options')), 'Shop manager can save shop settings');
ob_start(); odp_growth_admin(); $html = ob_get_clean();
$check(str_contains($html, 'name="_wpnonce"') && str_contains($html, 'odp-campaign'), 'Admin form includes CSRF nonce and campaign builder');
delete_option('odp_growth');
WP_CLI::success('Shop management integration checks passed.');
