# Generated by Django 5.2.16 on 2026-07-12 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0005_accessevent_auditevent_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=40)),
                ('selected_block_ids', models.JSONField(default=list)),
                ('suggested_blocks', models.JSONField(default=list)),
                ('raw_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('provider', models.CharField(default='openai', max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studio_ai_suggestions', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studio_ai_decisions', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_suggestions', to='lexamora_studio.prompt')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_suggestions', to='lexamora_studio.revision')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_suggestions', to='lexamora_studio.workspace')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=20)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('output_chars', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_usage', to='lexamora_studio.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studio_ai_usage', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_usage', to='lexamora_studio.workspace')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
