# Generated by Django 5.2.16 on 2026-07-12 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0008_exportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocxImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('ACCEPTED', 'Accepted'), ('ERROR', 'Error')], default='PREVIEW', max_length=16)),
                ('parsed_data', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studio_accepted_docx_imports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_imports', to='lexamora_studio.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studio_docx_imports', to=settings.AUTH_USER_MODEL)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docx_imports', to='lexamora_studio.asset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docx_imports', to='lexamora_studio.workspace')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
