# Generated by Django 5.2.16 on 2026-07-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0009_docx_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='lexamora_studio.prompt'),
        ),
    ]
