# Generated by Django 5.2.16 on 2026-07-13 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0012_prompt_language_translation_and_ai_undo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('VIEWER', 'View'), ('EDITOR', 'Edit'), ('CONTROLLER', 'Full control')], default='VIEWER', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studio_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='lexamora_studio.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'user__username', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='studio_unique_project_member')],
            },
        ),
    ]
