# Generated by Django 5.2.16 on 2026-07-14 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_owner_exclusions(apps, schema_editor):
    exclusion = apps.get_model('lexamora_studio', 'ProjectAccessExclusion')
    exclusion.objects.filter(user_id=models.F('project__workspace__owner_id')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0020_workspace_avatar_and_project_access_exclusion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='purged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purged_studio_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(remove_owner_exclusions, migrations.RunPython.noop),
    ]
