# Generated by Django 5.2.16 on 2026-07-14 08:14

import django.db.models.deletion
from django.db import migrations, models


def propagate_existing_languages(apps, schema_editor):
    Workspace = apps.get_model('lexamora_studio', 'Workspace')
    Project = apps.get_model('lexamora_studio', 'Project')
    Episode = apps.get_model('lexamora_studio', 'Episode')
    for project in Project.objects.all():
        language = (project.original_language or 'EN').upper()
        Project.objects.filter(pk=project.pk).update(
            documentation_language=language, dialogue_language=language, prompt_language=language,
        )
        Episode.objects.filter(project_id=project.pk).update(language=language)
    for workspace in Workspace.objects.all():
        language = (
            Project.objects.filter(workspace_id=workspace.pk).exclude(original_language='')
            .values_list('original_language', flat=True).first() or 'EN'
        ).upper()
        Workspace.objects.filter(pk=workspace.pk).update(
            documentation_language=language, dialogue_language=language, prompt_language=language,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0021_workspace_purged_at_workspace_purged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_avatar_for', to='lexamora_studio.asset'),
        ),
        migrations.AddField(
            model_name='episode',
            name='language',
            field=models.CharField(default='EN', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='dialogue_language',
            field=models.CharField(default='EN', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_language',
            field=models.CharField(default='EN', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='prompt_language',
            field=models.CharField(default='EN', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='audio_prompt_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='dialogue_language',
            field=models.CharField(default='EN', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='documentation_language',
            field=models.CharField(default='EN', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='image_prompt_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='prompt_language',
            field=models.CharField(default='EN', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='video_prompt_template',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(propagate_existing_languages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aimodelprofile',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Photo'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text')], max_length=16),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('IMAGE', 'Photo'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text')], max_length=16),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='scope',
            field=models.CharField(choices=[('ALL', 'All prompt types'), ('IMAGE', 'Photo'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text')], default='ALL', max_length=16),
        ),
    ]
