# Generated by Django 5.2.16 on 2026-07-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0023_workspace_text_prompt_template_emaildeliverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cover_for', to='lexamora_studio.asset'),
        ),
    ]
