# Generated by Django 5.2.16 on 2026-07-14 17:40

from django.db import migrations, models


def backfill_asset_links(apps, schema_editor):
    Asset = apps.get_model('lexamora_studio', 'Asset')
    Character = apps.get_model('lexamora_studio', 'Character')
    Project = apps.get_model('lexamora_studio', 'Project')
    AssetProject = Asset.projects.through
    CharacterReference = Character.reference_assets.through
    Prompt = apps.get_model('lexamora_studio', 'Prompt')
    PromptReference = Prompt.reference_assets.through
    Scene = apps.get_model('lexamora_studio', 'Scene')
    SceneReference = Scene.reference_assets.through

    for asset in Asset.objects.select_related(
        'project', 'scene__episode__project', 'character__project', 'prompt__scene__episode__project'
    ).iterator():
        project_ids = {
            value for value in (
                asset.project_id,
                asset.scene.episode.project_id if asset.scene_id else None,
                asset.character.project_id if asset.character_id else None,
                asset.prompt.scene.episode.project_id if asset.prompt_id else None,
            ) if value
        }
        for project_id in project_ids:
            AssetProject.objects.get_or_create(asset_id=asset.id, project_id=project_id)
        if asset.scene_id:
            SceneReference.objects.get_or_create(scene_id=asset.scene_id, asset_id=asset.id)
        if asset.character_id:
            CharacterReference.objects.get_or_create(character_id=asset.character_id, asset_id=asset.id)
        if asset.prompt_id:
            PromptReference.objects.get_or_create(prompt_id=asset.prompt_id, asset_id=asset.id)

    for character in Character.objects.exclude(avatar_asset_id__isnull=True).select_related('project').iterator():
        CharacterReference.objects.get_or_create(character_id=character.id, asset_id=character.avatar_asset_id)
        AssetProject.objects.get_or_create(asset_id=character.avatar_asset_id, project_id=character.project_id)

    for project in Project.objects.exclude(cover_asset_id__isnull=True).iterator():
        AssetProject.objects.get_or_create(asset_id=project.cover_asset_id, project_id=project.id)


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0024_project_cover_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='media_assets', to='lexamora_studio.project'),
        ),
        migrations.AddField(
            model_name='character',
            name='reference_assets',
            field=models.ManyToManyField(blank=True, related_name='referenced_by_characters', to='lexamora_studio.asset'),
        ),
        migrations.AddField(
            model_name='scene',
            name='reference_assets',
            field=models.ManyToManyField(blank=True, related_name='referenced_by_scenes', to='lexamora_studio.asset'),
        ),
        migrations.RunPython(backfill_asset_links, migrations.RunPython.noop),
    ]
