# Generated by Django 5.2.16 on 2026-07-14 17:40

from django.db import migrations, models


def backfill_asset_links(apps, schema_editor):
    Asset = apps.get_model('lexamora_studio', 'Asset')
    Character = apps.get_model('lexamora_studio', 'Character')
    Project = apps.get_model('lexamora_studio', 'Project')

    for asset in Asset.objects.select_related(
        'project', 'scene__episode__project', 'character__project', 'prompt__scene__episode__project'
    ).iterator():
        project_ids = {
            value for value in (
                asset.project_id,
                asset.scene.episode.project_id if asset.scene_id else None,
                asset.character.project_id if asset.character_id else None,
                asset.prompt.scene.episode.project_id if asset.prompt_id else None,
            ) if value
        }
        if project_ids:
            asset.projects.add(*Project.objects.filter(id__in=project_ids))
        if asset.scene_id:
            asset.scene.reference_assets.add(asset)
        if asset.character_id:
            asset.character.reference_assets.add(asset)
        if asset.prompt_id:
            asset.prompt.reference_assets.add(asset)

    for character in Character.objects.exclude(avatar_asset_id__isnull=True).select_related('project').iterator():
        character.reference_assets.add(character.avatar_asset_id)
        character.avatar_asset.projects.add(character.project)

    for project in Project.objects.exclude(cover_asset_id__isnull=True).iterator():
        project.cover_asset.projects.add(project)


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0024_project_cover_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='media_assets', to='lexamora_studio.project'),
        ),
        migrations.AddField(
            model_name='character',
            name='reference_assets',
            field=models.ManyToManyField(blank=True, related_name='referenced_by_characters', to='lexamora_studio.asset'),
        ),
        migrations.AddField(
            model_name='scene',
            name='reference_assets',
            field=models.ManyToManyField(blank=True, related_name='referenced_by_scenes', to='lexamora_studio.asset'),
        ),
        migrations.RunPython(backfill_asset_links, migrations.RunPython.noop),
    ]
