# Generated by Django 5.2.16 on 2026-07-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0026_scene_type_and_production_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalgeneration',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='description_dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='description_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='name_dialogue',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='character',
            name='name_prompt',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='character',
            name='visual_description_dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='visual_description_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='delivery_documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='delivery_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='speaker_documentation',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='speaker_prompt',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='text_documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='text_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='actions_dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='actions_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='description_dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='description_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='hook_dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='hook_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='location_dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='location_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='performance_notes_dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='performance_notes_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='title_dialogue',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='scene',
            name='title_prompt',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
