# Generated by Django 5.2.16 on 2026-07-15 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0028_project_description_recommendedtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='avatar_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_avatar_for', to='lexamora_studio.asset'),
        ),
        migrations.AddField(
            model_name='episode',
            name='cover_assets',
            field=models.ManyToManyField(blank=True, related_name='cover_for_episodes', to='lexamora_studio.asset'),
        ),
    ]
