# Generated by Django 5.2.16 on 2026-07-15 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0034_ai_generation_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='QUEUED', max_length=16)),
                ('request_prompt', models.TextField()),
                ('options', models.JSONField(default=dict)),
                ('reference_asset_ids', models.JSONField(default=list)),
                ('provider_model', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_generation_jobs', to='lexamora_studio.aimodelprofile')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_generation_jobs', to='lexamora_studio.prompt')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studio_image_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('result_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='lexamora_studio.asset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_generation_jobs', to='lexamora_studio.workspace')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='studio_img_job_queue')],
            },
        ),
    ]
