# Generated by Django 5.2.16 on 2026-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0040_studiouserpreference_model_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiouserpreference',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studiouserpreference',
            name='translation_language',
            field=models.CharField(default='EN', max_length=16),
        ),
    ]
