# Generated by Django 5.2.16 on 2026-07-19 09:10

import lexamora_studio.models
import lexamora_studio.storage_backend
from django.conf import settings
from django.db import migrations, models


def queue_existing_media(apps, schema_editor):
    Asset = apps.get_model("lexamora_studio", "Asset")
    Asset.objects.filter(content_type__startswith="video/").update(processing_status="QUEUED")
    Asset.objects.filter(content_type__startswith="audio/").update(processing_status="QUEUED")


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0044_movie_timeline_schema_and_revisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='duration_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='media_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='processing_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processing_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='proxy_file',
            field=models.FileField(blank=True, max_length=500, storage=lexamora_studio.storage_backend.PrivateStudioStorage(), upload_to=lexamora_studio.models.studio_proxy_path),
        ),
        migrations.AddField(
            model_name='asset',
            name='waveform_file',
            field=models.FileField(blank=True, max_length=500, storage=lexamora_studio.storage_backend.PrivateStudioStorage(), upload_to=lexamora_studio.models.studio_waveform_path),
        ),
        migrations.RunPython(queue_existing_media, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['processing_status', 'created_at'], name='studio_media_queue'),
        ),
    ]
