# Generated by Django 5.2.16 on 2026-07-19 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0045_asset_duration_ms_asset_media_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRenderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('profile', models.CharField(choices=[('DRAFT_720', 'Draft 720p'), ('REVIEW_1080', 'Review 1080p')], default='DRAFT_720', max_length=20)),
                ('aspect_ratio', models.CharField(max_length=12)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('fps', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movie_render_jobs', to='lexamora_studio.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_render_jobs', to='lexamora_studio.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_render_jobs', to=settings.AUTH_USER_MODEL)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='render_jobs', to='lexamora_studio.movietimeline')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='studio_render_queue')],
            },
        ),
    ]
