# Generated by Django 5.2.16 on 2026-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexamora_studio', '0046_movierenderjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierenderjob',
            name='audio_profile',
            field=models.CharField(choices=[('ORIGINAL', 'Original mix'), ('BALANCED', 'Balanced'), ('CLEAN_SPEECH', 'Clean speech')], default='CLEAN_SPEECH', max_length=20),
        ),
        migrations.AddField(
            model_name='movierenderjob',
            name='target_lufs',
            field=models.SmallIntegerField(default=-16),
        ),
    ]
