# Generated by Django 5.2.16 on 2026-07-19

from django.db import migrations, models

import lexamora_studio.models
import lexamora_studio.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ("lexamora_studio", "0047_movierenderjob_audio_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="filmstrip_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                storage=lexamora_studio.storage_backend.PrivateStudioStorage(),
                upload_to=lexamora_studio.models.studio_filmstrip_path,
            ),
        ),
    ]
